export default function HomePage() {
    return (
        <div
            className="
            mx-auto
            pt-[calc(100px+100px)]
            flex
            justify-center
            items-center
            w-full
            flex-col
            h-fit
            min-h-[500px]
            ">
            <div className="
                justify-center
                items-center
                flex
                flex-col
                max-w-[1300px]">
                <div
                    className=
                    "mb-[30px]"
                >
                    <h1
                        className="
                    m-auto
                    text-center
                    font-normal
                    text-[20px]
                    sm:text-[60px]
                    ">Agora você pode ter <br />
                        <span
                            className="
                        text-[40px]
                        sm:text-[80px] 
                        font-bold"
                        >o site dos seus sonhos</span></h1>
                </div>
                <div
                    className="
                flex
                gap-6
                ">
                    <button
                        className="
                    py-2
                    px-4
                    sm:py-4
                    sm:px-8
                    rounded-[6px]
                    bg-gradient-to-r 
                    from-[#7d1ebd]
                    to-[#1e316f]"
                    >Quero um site</button>
                    <button
                        className="
                    py-2
                    px-4
                    sm:py-4
                    sm:px-8"
                    >Conheça mais</button>
                </div>
                <div
                    className="
                mt-[80px]
                font-thin"
                >scroll to more
                </div>
            </div>
            <div className="
                my-[30px]
                py-[30px]
                justify-center
                items-center
                flex
                flex-col
                bg-[#161616]
                w-full
                max-w-[100vw]
                ">
                <div
                    className="
                my-[40px]
                flex
                w-fit
                h-fit
                max-w-[1300px]
                max-h-fit
                justify-center
                shadow-[#090909]
                shadow-lg
                flex-wrap"
                >
                    <div
                        className="
                     w-[250px]
                     h-[350px]
                     bg-[#bea860]
                     flex
                     justify-center
                     items-center
                     "
                    >card</div>
                    <div
                        className="
                     w-[250px]
                     h-[350px]
                     bg-[#c96161]
                     flex
                     justify-center
                     items-center
                     "
                    >card</div>
                    <div
                        className="
                     w-[250px]
                     h-[350px]
                     bg-[#5694de]
                     flex
                     justify-center
                     items-center
                     "
                    >card</div>
                </div>
            </div>
        </div>
    )
}